print('Day converter Program')
data = input('Enter number :')
n = int(data)
m = int(n / 60)
h = int(m / 60)
s = int(n % 60)
m1 = int(m % 60)
print('Hours =' ,h)
print('minute =' ,m1)
print('seconds =' ,s)