"""name = input('what is your name? \n')
surname = input('what is your surname? \n')
year = input('enter your year? \n')
student_id = input('what is your student id ? \n')
print('%s'% name)
print('%s'% surname)
print('%s'% year)
print('%s'% student_id)"""

"""x = 20
y = 35.24
z = 1j
a = float(x)
b = int(y)
c = complex(x)
print('a = %s'% a)
print('b = %s'% b)
print('c = %s'% c)"""

number_1 = input('enter number 1 \n')
number_2 = input('enter number 2 \n')
number_3 = input('enter number 3 \n')
number_4 = input('enter number 4 \n')
number_5 = input('enter number 5 \n')
a1 = float(number_1)
a2 = complex(number_1)
a3 = float(number_2)
a4 = complex(number_2)
a5 = float(number_3)
a6 = complex(number_3)
a7 = float(number_4)
a8 = complex(number_4)
a9 = float(number_5)
a10 = complex(number_5)
print('float of 1 = %.1f'%a1)
print('complex of 1 = %s'%a2)
print('float of 2 = %.1f'%a3)
print('complex of 2 = %s'%a4)
print('float of 3 = %.1f'%a5)
print('complex of 3 = %s'%a6)
print('float of 4 = %.1f'%a7)
print('complex of 4 = %s'%a8)
print('float of 5 = %.1f'%a9)
print('complex of 5 = %s'%a10)